global using AutoMapper;
global using IdentityServer.Application.Common;
global using IdentityServer.Application.Mapper.Converters;
global using IdentityServer.Application.Models;
global using IdentityServer.Domain.Entities;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Security.Claims;