version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_data:/var/data/mongo
  
  identitydb:
    container_name: identitydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CacheDiveExperimentDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - identity_data:/var/data/postgres
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@techalley.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApplicationDatabase:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
  
  identityserver.api:
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=localhost;Database=IdentityServerDb;User Id=postgres;Password=postgres;Integrated Security=true;Pooling=true"
    ports:
      - "8001:80"