version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_data:/data/db
  
  identitydb:
    container_name: identitydb
    privileged: true
    environment:
      SA_PASSWORD: "mcbv3n12!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApplicationDatabase:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"